name = "RHGV Servidor Mods"
author = "Ramiro Haro"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6ae1c271fba23162048e81a5e229667ee397a5291d47737e4a451750d5b36e4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
