name = "RHGV Servidor Mods"
author = "Ramiro Haro"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4130a8351a39fb53ce6075c8801c3534dd63e5287bb59ec94be357f274259172"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
