name = "RHGV Servidor Mods"
author = "Ramiro Haro"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb620cb9833d19541da4964179f341427e9acf1ab22b52aa25b72221ec6a725e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
